spring:


  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    password: java
    username: java
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create

